### ISSUE TITLE
Transaction functions erroring in 0.4.2

### ISSUE THREAD

**Issue by christroutner** [Bitcoin-com/wormholecash#5]
I just upgraded from npm package 0.2.4 to 0.4.2 and all my working code using the `Wormhole.Transaction` library returns some variation of this error message:

```
(node:22199) UnhandledPromiseRejectionWarning: TypeError: wormhole.Transaction.managed is not a function
    at createManagedToken (/home/trout/work/bch/bch-tests/create-managed-token/index.js:9:45)
    at Object.<anonymous> (/home/trout/work/bch/bch-tests/create-managed-token/index.js:31:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

The important takeway is "**is not a function**". I used util.inspect() and every Transaction function is showing a value of `undefined`.

I looked at the `Transaction.js` library for syntax errors but didn't spot anything. I suspect there may be a syntax error that prevents the functions from attaching to the constructor.

**Comment by christroutner** [comment]
Just confirmed. I was able to revert the wormholecash library to 0.2.4 and run [this example app](https://github.com/christroutner/bch-tests/blob/unstable/create-managed-token/index.js) successfully. But upgrading to 0.4.2 results in the above error.

**Comment by christroutner** [comment]
Did a bit more regression testing. 0.4.1 works, but 0.4.2 breaks as described above. So the issue seems to be isolated to this most recent npm library version.

**Comment by cgcardona** [comment]
Your code is great. Really nice work. I wanted to point out a couple of things. 

First, `Wormhole` is [a superset](https://github.com/Bitcoin-com/wormholecash/blob/master/src/Wormhole.js#L6) of `BITBOXCli`. So in nearly all cases you can replace `BITBOX` in your code w/ `Wormhole`. For example in your [changeAddrFromMnemonic](https://github.com/christroutner/bch-tests/blob/master/send-bch/index.js#L95) you could use `Wormhole` instead of `BITBOX`.

```js
let rootSeed = Wormhole.Mnemonic.toSeed(mnemonic);

// master HDNode
let masterHDNode = Wormhole.HDNode.fromSeed(rootSeed, 'testnet');

// HDNode of BIP44 account
let account = Wormhole.HDNode.derivePath(masterHDNode, "m/44'/145'/0'");

// derive the first external change address HDNode which is going to spend utxo
let change = Wormhole.HDNode.derivePath(account, "0/0");

```
The place that you can't yet replace `BITBOX` w/ `Wormhole` is any method which makes a network request. Currently `bitbox-cli` calls rest.bitcoin but `wormholecash` calls your local wormhole full node. That will change after sept 1st when we launch the wormhole endpoints on rest.bitcoin.

Second, I'm removing the `Configuration`, `Transaction`, and `Wallet` classes from `wormholecash` and the REST endpoints. All the Wormhole functionality is available over the `DataRetrieval`, `PayloadCreation`, and `RawTransactions` classes and endpoints which don't require keeping keys on a full node.

This will encourage people to write apps which securely store their keys and it will allow us to host the Wormhole endpoints on rest.bitcoin as were not needing to store anyones keys.

I'm going to be deprecating the existing Wormhole tutorial series and creating an improved one.

Here are how I'm doing all the transaction types w/ the new syntax

* [simple send](https://gist.github.com/cgcardona/0febcfbc355bf1885f79e74e83a25cfe)
* [change issuer](https://gist.github.com/cgcardona/e6ba4e5e9fd09cb790706ffa72112eaa)
* [close crowd sale](https://gist.github.com/cgcardona/b1e500324cd0536a3ca2dd63aa9cf888)
* [crowd sale](https://gist.github.com/cgcardona/2b35e5ca74e1c157288f98a93c7b4aed)
* [fixed token](https://gist.github.com/cgcardona/86a76cff53f4c6edead1335fd632cdeb)
* [grant tokens](https://gist.github.com/cgcardona/68f9247584ca13ca9d3647e736d79033)
* [managed token](https://gist.github.com/cgcardona/e678b3674450863a1bd921770b0cbe95)
* [participate crowd sale](https://gist.github.com/cgcardona/444b7fea7ac95ef0afff431fd05886ec)
* [revoke tokens](https://gist.github.com/cgcardona/1413ff6a5b55c1b9da21671e807247b3)
